# Vector Operations

In [1]:
import numpy as np

In [2]:
vect1 = np.array([1,2,3,4])
vect2 = np.array([5,6,7,8])

print("\nVector Addition",vect1 + vect2)
print("\nVector Multiplication",vect1 * vect2)

# Dot Product Similarity
print("\nVector Dot Product",np.dot(vect1,vect2))

# Cosine Similarity
angle = np.arccos(np.dot(vect1, vect2) / (np.linalg.norm(vect1) * np.linalg.norm(vect2)))
print("\nCosine Similarity(Angle)",angle)

# 




Vector Addition [ 6  8 10 12]

Vector Multiplication [ 5 12 21 32]

Vector Dot Product 70

Cosine Similarity(Angle) 0.25019592042251176


# Vectorized Operation

In [3]:
food = np.array(['BirYani', 'ChoWmeIn', 'mOMo', 'CHicKen', 'MuTTon'])

vectorized_upper = np.vectorize(str.upper) 
print("\nVectorized Upper Case",vectorized_upper(food))

vectorized_lower = np.vectorize(str.lower) 
print("\nVectorized Upper Case",vectorized_lower(food))



Vectorized Upper Case ['BIRYANI' 'CHOWMEIN' 'MOMO' 'CHICKEN' 'MUTTON']

Vectorized Upper Case ['biryani' 'chowmein' 'momo' 'chicken' 'mutton']


# Broadcasting

In [4]:
sales_data = np.array([
                       [1, 150000, 180000, 200000, 250000], # Arsalan
                       [2, 120000, 140000, 160000, 190000], # Chowman
                       [3, 200000, 230000, 260000, 300000], # Dominos
                       [4, 180000, 210000, 240000, 270000], # Burger King
                       [5, 160000, 180000, 205000, 230000] # BTech Chaiwala
])

monthly_avg = sales_data[:, 1:] / 12  # Broadcasting....Scalar(12) iterated to each and every element of the Numpy Array 
print("\nMonthly Average Income\n",monthly_avg)


Monthly Average Income
 [[12500.         15000.         16666.66666667 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15000.         17083.33333333 19166.66666667]]
