# Convert a 1D array into a 2D array (how to add a new axis to an array)

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])
print(arr.shape)

#  to add a new axis
# 1D => 2D
arr2 = arr[np.newaxis,:] # np.newaxis => increases the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.
print(arr2.shape)
# 2D => 3D
arr3 = arr2[np.newaxis,:]
print(arr3.shape)

# for a column vector, you can insert an axis along the second dimension
# col_vec = arr2[:,np.newaxis]
# print(col_vec.shape)

# expand an array by inserting a new axis at a specified position
a = np.array([3,5,1,8,6,9,0])
a2 = np.expand_dims(a, axis = 1) # at index position 1
print(a2.shape)

a3 = np.expand_dims(a, axis = 0) # at index position 0
print(a3.shape)

(6,)
(1, 6)
(1, 1, 6)
(7, 1)
(1, 7)


# Split an array into several smaller arrays

In [17]:
ar = np.arange(1,25).reshape(2,12)
print(ar)

print('\nsplit this array into three equally shaped arrays')
print(np.hsplit(ar, 3))

print('\nsplit your array after the third and fourth column')
print(np.hsplit(ar,(3,4)))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]

split this array into three equally shaped arrays
[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]

split your array after the third and fourth column
[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]


# Reverse an array

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print('\nReverse 1D array')
rev_arr = np.flip(arr)
print(rev_arr)

arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print('\nReverse 2D array')
rev_arr2 = np.flip(arr_2d)
print(rev_arr2)

print('\nreverse only the rows')
rev_rows = np.flip(arr_2d, axis=0)
print(rev_rows)

print('\nreverse only the column')
rev_col = np.flip(arr_2d, axis=1)
print(rev_col)


Reverse 1D array
[8 7 6 5 4 3 2 1]

Reverse 2D array
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]

reverse only the rows
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

reverse only the column
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
