## Numpy Array and Basics

In [1]:
import numpy as np

### Creating array from list

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("1d array: ",arr_1d)

arr_2d = np.array([[1,2,3],
                   [4,5,6]])
print("2D ARRAY:\n",arr_2d)

1d array:  [1 2 3 4 5]
2D ARRAY:
 [[1 2 3]
 [4 5 6]]


### List vs Numpy Array


In [3]:
py_list = [1,2,3]
print("Python List Multiplication: ",py_list*2)

np_arr = np.array([1,2,3]) #element wise multiplication
print("Numpy Array Multiplication: ",np_arr*2)

#Checking Efficiency Between The Two

import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("\n List Operation Time: ", time.time() - start)

start = time.time()
np_arr = np.arange(10000000) * 2  #arange() generates array withing the 'specified' range like 10000000
print("\n Numpy Array Operation Time: ", time.time() - start)



Python List Multiplication:  [1, 2, 3, 1, 2, 3]
Numpy Array Multiplication:  [2 4 6]

 List Operation Time:  1.4689276218414307

 Numpy Array Operation Time:  0.07024359703063965


## Creating Array from Scratch

In [4]:
## Zeros Matrix
zeros = np.zeros((4,4))
print("Zero Matrix:\n", zeros) 

## Ones Matrix
ones = np.ones((5,4))
print("Identity(1's) Matrix:\n", ones) 

## Constant Matrix
full = np.full((3,3),9)
print("Constant/Full Matrix:\n", full) 

## Random Value Matrix
r = np.random.random((2,2))
print("Random Value Matrix:\n", r) 

## Sequence(Generates Array)
seq = np.arange(0,10,2)
print("Sequence:\n", seq) 

## Identity Matrix
iden = np.eye(3)
print("Identity:\n", iden)

Zero Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Identity(1's) Matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Constant/Full Matrix:
 [[9 9 9]
 [9 9 9]
 [9 9 9]]
Random Value Matrix:
 [[0.99679086 0.94806158]
 [0.31470467 0.5438827 ]]
Sequence:
 [0 2 4 6 8]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Vector, Matrix and Tensor 

In [5]:
# 1D Array => Vector
vector = np.array([1,2,3])
print("Vector:\n", vector)

# 2D Array => Matrix
matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix:\n", matrix)

# Multi Dimensional Array => Tensor
tensor = np.array([[[1,2],[3,4]], 
                  [[5,6],[7,8]],
                  [[9,10],[11,12]]])
print("Tensor/Multi-Dimensional Array:\n", tensor)


Vector:
 [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor/Multi-Dimensional Array:
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


## Array Properties

In [6]:
matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Shape:\n", matrix.shape) # No. of rows and columns
print("Dimension:\n", matrix.ndim) # Array Dimension
print("Size:\n", matrix.size) # No. elements in the Matrix
print("Data Type:\n", matrix.dtype) # Data Type


Shape:
 (2, 3)
Dimension:
 2
Size:
 6
Data Type:
 int64


## Array Reshaping

In [7]:
arr = np.arange(12)
print("Original Array:\n", arr)

# Array Reshaping 
reshaped = arr.reshape((3,4)) # arr.reshape((row,col))
print("Reshaped Array:\n", reshaped)

# Converts to Single Line
flat = reshaped.flatten()
print("Flattened Array:\n", flat)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("Raveled Array:\n", raveled)

# Transpose
trans = reshaped.T
print("Transposed Array:\n", trans)


Original Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
