## Numpy Array Operations

In [1]:
import numpy as np

## Slicing - 1D ARRAY


In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing:\n", arr[3:8])
print("Step Slicing:\n", arr[3:8:2])
print("Negative Slicing:\n", arr[::-1])


Basic Slicing:
 [4 5 6 7 8]
Step Slicing:
 [4 6 8]
Negative Slicing:
 [10  9  8  7  6  5  4  3  2  1]


## Slicing - 2D ARRAY

In [3]:
arr2 = np.array([[1,2,3],  # ROW 0
                 [4,5,6],  # ROW 1
                 [7,8,9]]) # ROW 2
print("Specific Element:",arr2[0,2]) # arr2[row,col]
print("Entire Row:",arr2[2])  # arr2[row]
print("Entire Column:",arr2[:,1])  # arr2[row:,col]

Specific Element: 3
Entire Row: [7 8 9]
Entire Column: [2 5 8]


## Sorting Array 1D & 2D

In [4]:
unsorted = np.array([3,5,6,1,4,9,8,5,0,7])
print("Sorted:",np.sort(unsorted)) # Default Sorting: Ascending Order

arr2_unsorted = np.array([[8,6],
                          [1,3],
                          [6,7],
                          [5,2]])
print("Column-Wise Sorting:\n",np.sort(arr2_unsorted, axis=0))
print("Row-Wise Sorting:\n",np.sort(arr2_unsorted, axis=1))


Sorted: [0 1 3 4 5 5 6 7 8 9]
Column-Wise Sorting:
 [[1 2]
 [5 3]
 [6 6]
 [8 7]]
Row-Wise Sorting:
 [[6 8]
 [1 3]
 [6 7]
 [2 5]]


## Filter

In [5]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
even_num = num[num % 2 == 0]
print("Even Numbers:", even_num)


Even Numbers: [ 2  4  6  8 10]


## Filtering with Mask

In [6]:
mask = num < 7  # Directly stores the evaluating condition
print("Numbers less than 7:", num[mask])

Numbers less than 7: [1 2 3 4 5 6]


## Fancy Indexing vs np.where()

In [7]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
indices = [3, 7, 9]
print("Fancy Indexing:", num[indices])

where_output = np.where(num%2==0) # Like mask, but not a mask as it first checks whether the condition in T or F
print("Where Clause Result:",num[where_output])

cond_arr = np.where(num%2==0, num*3, num) # np.where(main condition, x val, y val(basis of which array))
print("Conditional Array:", cond_arr)

Fancy Indexing: [ 4  8 10]
Where Clause Result: [ 2  4  6  8 10]
Conditional Array: [ 1  6  3 12  5 18  7 24  9 30]


## Combining Data

In [8]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

add = a1 + a2 # simple addition of elements
print("Simple Addition:",add)

combine = np.concatenate((a1, a2)) # Adds/Combines the Data
print("Combined Data:",combine)

Simple Addition: [5 7 9]
Combined Data: [1 2 3 4 5 6]


## Array Compatibility Testing

In [9]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a3 = np.array([7,8,9,10])

print("Array Compatibility?",a1.shape == a2.shape) # Same Dimension
print("Array Compatibility?",a1.shape == a3.shape) # Dimension Differs

Array Compatibility? True
Array Compatibility? False


## Data Addition - Column-Wise & Row-Wise

In [10]:
original = np.array([[1,2,3],
                     [4,5,6]])
new_row = np.array([[1,8,5]])

with_new_row = np.vstack((original, new_row))
print("Data Adding Row-Wise:\n",with_new_row)

new_col = np.array([[8],
                    [9],
                    ])
with_new_col = np.hstack((original, new_col))
print("Data Adding Column-Wise:\n",with_new_col)


Data Adding Row-Wise:
 [[1 2 3]
 [4 5 6]
 [1 8 5]]
Data Adding Column-Wise:
 [[1 2 3 8]
 [4 5 6 9]]


## Data Deletion

In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
deleted = np.delete(arr, arr[2:7:2])
print("Array after Deletion:",deleted)

Array after Deletion: [ 1  2  3  5  7  9 10]
